Add document:upsert
kuzzleio/sdk-jvm pull request #38
Opened 2020-12-28 14:59 UTC by Yoann-Abbes

## What does this PR do ?

Add document:upsert https://github.com/kuzzleio/sdk-jvm/issues/37

### Other changes

Revert wrong change on `build.gradle.kts`
Fix mUpdate and updateByQuery doc

### Boyscout

2021-01-06 09:11 UTC, scottinet requested changes

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +title: upsert
Missing description

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +| `_id`        | <pre>String</pre>                            | ID of the udated document                   |
```suggestion
| `_id`        | <pre>String</pre>                            | ID of the updated document                   |
```

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +| `defaults` | <pre>ConcurrentHashMap<String, Object><br/>(`{}`)        | (optional) fields to add to the document if it gets created    |
```suggestion
| `defaults` | <pre>ConcurrentHashMap<String, Object><br/>(`{}`)        | Fields to add to the document if it gets created    |
```

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +| `defaults` | <pre>ConcurrentHashMap<String, Any?><br/>(`{}`)        | (optional) fields to add to the document if it gets created    |
```suggestion
| `defaults` | <pre>ConcurrentHashMap<String, Any?><br/>(`{}`)        | Fields to add to the document if it gets created    |
```

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +A `ConcurrentHashMap<String, Any?>` with the following properties:
```suggestion
A `ConcurrentHashMap<String, Any?>` object, with the following properties:
```

2021-01-06 09:11 UTC, scottinet commented on doc/1/controllers/document/upsert/index.md
> +| `_id`        | <pre>String</pre>                            | ID of the udated document                   |
```suggestion
| `_id`        | <pre>String</pre>                            | ID of the updated document                   |
```

2021-01-15 11:03 UTC, Leodau approved these changes

2021-01-15 14:23 UTC, Shiranuit approved these changes

2021-01-15 14:54 UTC, Aschen requested changes

2021-01-21 00:01 UTC, alexandrebouthinon requested changes

2021-01-21 00:01 UTC, alexandrebouthinon commented on doc/1/controllers/document/upsert/snippets/upsert-kotlin.kt
> +  .get()
Missing indentation

2021-01-21 09:19 UTC, alexandrebouthinon approved these changes

2021-01-21 12:18 UTC, Aschen approved these changes

2021-02-22 09:04 UTC, scottinet approved these changes

2021-02-22 09:05 UTC, merged