Add auth:searchApiKeys
kuzzleio/sdk-jvm pull request #39
Opened 2020-12-29 11:00 UTC by Yoann-Abbes

## What does this PR do ?

Add auth:searchApiKeys API action https://github.com/kuzzleio/sdk-jvm/issues/29

### Other changes

Reverse wrong change on `build.gradle.kts`
Re-indent doc, and add comments

### Boyscout

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +<SinceBadge version="7.1.0" />
```suggestion
<SinceBadge version="auto-version" />
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +Searches API keys for the currently loggued user.
```suggestion
Searches API keys for the currently logged user.
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +| `size`     | <pre>Integer</pre>    | (optionnal) Maximum number of documents to retrieve per page     |
```suggestion
| `from`     | <pre>Integer</pre><br/>(`0`)     | (optional) Offset of the first document to fetch   |
| `size`     | <pre>Integer</pre>    | (optional) Maximum number of documents to retrieve per page     |
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +The search query to apply to API keys content, using [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
The search query to apply to API keys content, using the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +If left empty, the result will return all available API keys of the currently loggued user.
```suggestion
If left empty, the result will return all available API keys for the currently logged user.
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +| `size`     | <pre>Int</pre>    | (optionnal) Maximum number of documents to retrieve per page     |
```suggestion
| `from`     | <pre>Int</pre><br/>(`0`)     | (optional) Offset of the first document to fetch   |
| `size`     | <pre>Int</pre>    | (optional) Maximum number of documents to retrieve per page     |
```

2021-01-06 09:06 UTC, scottinet commented on doc/1/controllers/auth/search-api-keys/index.md
> +If left empty, the result will return all available API keys of the currently loggued user.
```suggestion
The search query to apply to API keys content, using the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.

If left empty, the result will return all available API keys of the currently logged user.
```

2021-01-06 09:07 UTC, scottinet requested changes
Documentation fixes (sorry I misclicked on "comment" instead of "request changes")

2021-01-06 12:37 UTC, scottinet approved these changes

2021-01-07 13:04 UTC, jenow commented on build.gradle.kts
> +    from(configurations.compileClasspath.get().map { if (it.isDirectory()) it else zipTree(it) })
lol.

2021-01-07 13:04 UTC, jenow approved these changes

2021-01-07 13:04 UTC, merged