Fix build gradle
kuzzleio/sdk-jvm pull request #81
Opened 2022-07-12 13:48 UTC by CustomEntity

## What does this PR do ?

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2022-07-12 13:54 UTC, Shiranuit commented on src/main/kotlin/io/kuzzle/sdk/protocol/Http.kt
> +                    this.setBody("JsonSerializer.serialize(payload)")
```suggestion
                    this.setBody(JsonSerializer.serialize(payload))
```
This should not be stringified

2022-07-19 09:50 UTC, Shiranuit requested changes
Good job, some comment about the naming of the SDK
You changed the SDK name without from `sdk-jvm-x.x.x-without-dependencies.jar` to `sdk-jvm-.x.x.x.jar`
And `sdk-jvm-.x.x.x.jar` to `sdk-jvm-x.x.x-with-dependencies.jar`

Here you can see that  `sdk-jvm-.x.x.x.jar` was with dependencies and you changed it to be without dependencies, once released on maven people that were importing ``sdk-jvm-.x.x.x` in their `pom.xml` or `build.gradle` will have issues because they will have missing dependencies.
We should keep the same naming as before to avoid confusing the users when they will be upgrading their version of the SDK.

Also can you please update the compatibility matrix in the `README.md`

2022-07-19 09:54 UTC, Shiranuit commented on build.gradle.kts
> +val ktorVersion = "1.3.2-1.4.0-rc"
Why did you downgrade the ktorVersion from `1.6.8` to `1.3.2-1.4.0-rc` ?

2022-07-21 08:02 UTC, CustomEntity commented
> Good job +1 some comment about the naming of the SDK You changed the SDK name without from `sdk-jvm-x.x.x-without-dependencies.jar` to `sdk-jvm-.x.x.x.jar` And `sdk-jvm-.x.x.x.jar` to `sdk-jvm-x.x.x-with-dependencies.jar`
> 
> Here you can see that `sdk-jvm-.x.x.x.jar` was with dependencies and you changed it to be without dependencies, once released on maven people that were importing `sdk-jvm-.x.x.x` in their `pom.xml` or `build.gradle` will have issues because they will have missing dependencies. We should keep the same naming as before to avoid confusing the users when they will be upgrading their version of the SDK.
> 
> Also can you please update the compatibility matrix in the `README.md`

FIxed in commit 7436193552a980bb2b476477d640bebe5ca5559f

2022-07-25 09:12 UTC, Shiranuit approved these changes

2022-07-25 14:27 UTC, Aschen reviewed
I have no experience with Gradle so if it's ok for @Shiranuit it's ok for me

2022-08-08 10:04 UTC, merged