Implemented #51
kuzzleio/sdk-jvm pull request #82
Opened 2022-07-21 07:46 UTC by CustomEntity

### How should this be manually tested?

Call BulkController#updateByQuery
  ...

2022-07-25 09:16 UTC, Shiranuit approved these changes
Nice Job 👍

2022-07-25 14:26 UTC, Aschen requested changes

2022-07-25 14:26 UTC, Aschen commented on doc/1/controllers/bulk/update-by-query/index.md
> +| `changesQuery`   | <pre>Map<String, Object></pre> | JSON representing the query of the changes to apply                            |
This is not a query but simply a list of changes. It should be named `changes`

2022-07-25 14:26 UTC, Aschen commented on doc/1/controllers/bulk/update-by-query/index.md
> +An Int containing the number of updated documents.
Use code formatting for anything coming from the code
```suggestion
An `Int` containing the number of updated documents.
```

2022-07-25 14:26 UTC, Aschen commented on doc/1/controllers/bulk/update-by-query/snippets/update-by-query-kotlin.kt
> +val changesQuery: Map<String, Any?> = HashMap<String, Any?>().apply {
`changesQuery` should be renamed to `changes`

2022-07-25 14:26 UTC, Aschen commented on src/main/kotlin/io/kuzzle/sdk/controllers/BulkController.kt
> +        changesQuery: Map<String, Any?>,
Same comment about naming

2022-07-25 14:26 UTC, Aschen commented on doc/1/controllers/bulk/update-by-query/index.md
> +  Map<String, Object> searchQuery,
Why are you not using the type defined in the code ? (`Any?`)

2022-12-29 21:06 UTC, Aschen commented
@CustomEntity Are you planning to finish this?

2023-01-04 16:37 UTC, Aschen approved these changes

2023-01-12 09:08 UTC, merged